/** Browser-only workflow; synthetic records and retained audit history.
 * Run from repository root: node frontend/check-ui.cjs
 * FRONTEND_URL defaults to the Docker website. No rate/security bypasses.
 */
const {chromium}=require('@playwright/test');
const assert=require('node:assert/strict');
const BASE_URL=process.env.FRONTEND_URL||'http://127.0.0.1:8095';
(async()=>{
 const browser=await chromium.launch({headless:true});const errors=[];
 async function newPage(){const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(()=>localStorage.setItem('kutumb-locale','en'));const page=await context.newPage();page.on('pageerror',e=>errors.push(String(e)));return page;}
 async function staff(email){const page=await newPage();await page.goto(BASE_URL+'/sign-in');await page.getByRole('button',{name:'Staff & department',exact:true}).click();await page.getByLabel('Official account email',{exact:false}).fill(email);await page.getByLabel('Password',{exact:false}).fill('DemoPass@123!');await page.getByRole('button',{name:'Sign in securely',exact:true}).click();await page.waitForURL(url=>!url.pathname.includes('sign-in'));return page;}
 async function decision(page,action,reason){await page.getByLabel(/^Action/).selectOption(action);await page.getByLabel('Evidence-based reason',{exact:false}).fill(reason);await page.getByRole('checkbox').check();const saved=page.waitForResponse(r=>r.url().endsWith('/action')&&r.request().method()==='POST');await page.getByRole('button',{name:'Confirm and record action'}).click();const response=await saved;assert.equal(response.status(),200,await response.text());}
 try{
  const resident=await newPage();await resident.goto(BASE_URL+'/sign-in');const mobile='9'+Date.now().toString().slice(-9);
  await resident.getByRole('button',{name:'Create an account',exact:true}).click();await resident.getByLabel('Your name',{exact:false}).fill('Synthetic UI Resident');await resident.getByLabel('Mobile number or Family ID',{exact:false}).fill(mobile);await resident.getByRole('button',{name:'Get verification code',exact:true}).click();await resident.getByLabel('One-time code',{exact:false}).fill('123456');await resident.getByRole('button',{name:'Verify and continue',exact:true}).click();await resident.waitForURL('**/my');console.log('PASS: resident account registration through OTP');
  await resident.goto(BASE_URL+'/apply/start');await resident.getByRole('button',{name:'Continue to application',exact:true}).click();await resident.getByLabel('Applicant name',{exact:false}).waitFor();const applicationId=resident.url().split('/').pop();await resident.getByLabel('Applicant name',{exact:false}).fill('Synthetic UI Resident');await resident.getByLabel('Contact mobile',{exact:false}).fill(mobile);await resident.getByRole('button',{name:'Save and continue',exact:true}).click();
  await resident.getByLabel('Address line',{exact:false}).fill('15 Synthetic Garden Society');await resident.getByLabel('Village / ward / locality',{exact:false}).fill('Navrangpura');await resident.getByLabel('Taluka / urban body',{exact:false}).fill('Ahmedabad City');await resident.getByLabel('District',{exact:false}).selectOption('Ahmedabad');await resident.getByLabel('PIN code',{exact:false}).fill('380009');await resident.getByRole('button',{name:'Save and continue',exact:true}).click();
  await resident.getByLabel('Date of birth',{exact:false}).fill('1994-07-15');await resident.getByRole('button',{name:'Add another member',exact:true}).click();await resident.getByLabel('Full name',{exact:false}).nth(1).fill('Synthetic UI Child');await resident.getByLabel('Date of birth',{exact:false}).nth(1).fill('2018-02-20');await resident.getByRole('button',{name:'Save and continue',exact:true}).click();await resident.getByRole('button',{name:'Save and continue',exact:true}).click();await resident.getByRole('checkbox').nth(0).check();await resident.getByRole('checkbox').nth(1).check();await resident.getByRole('button',{name:'Submit application',exact:true}).click();await resident.waitForURL('**/receipt');await resident.getByRole('heading',{name:'Application acknowledgement',exact:true}).waitFor();assert.match(await resident.locator('main').innerText(),/Submitted/);console.log('PASS: two-member registration, saved draft and durable receipt',applicationId);
  const verifier=await staff('verifier@demo.local');await verifier.goto(BASE_URL+'/staff/applications/'+applicationId);await decision(verifier,'start_review','Synthetic resident assertions reviewed for browser acceptance.');await decision(verifier,'verify','All required synthetic declarations independently verified.');await verifier.getByText('No decision action is currently available',{exact:false}).waitFor();console.log('PASS: verifier review and verification');
  const approver=await staff('approver@demo.local');await approver.goto(BASE_URL+'/staff/applications/'+applicationId);await decision(approver,'approve','Approved after separate verification of synthetic records.');await approver.getByText('No decision action is currently available',{exact:false}).waitFor();assert.match(await approver.locator('main').innerText(),/Implemented/);console.log('PASS: independent approval and registry implementation');
  await resident.goto(BASE_URL+'/my/family');await resident.getByRole('heading',{name:'Family members',exact:true}).waitFor();assert.match(await resident.locator('main').innerText(),/Synthetic UI Child/);await resident.goto(BASE_URL+'/schemes/family-services-assistance');await resident.getByRole('checkbox').check();const referralResponse=resident.waitForResponse(r=>r.url().endsWith('/scheme-applications')&&r.request().method()==='POST');await resident.getByRole('button',{name:'Send application referral',exact:true}).click();const referral=await(await referralResponse).json();assert.ok(referral.reference);console.log('PASS: connected scheme referral',referral.reference);
  const department=await staff('department@demo.local');await department.goto(BASE_URL+'/staff/payments');await department.locator('.payment-row').filter({hasText:referral.reference}).getByRole('button',{name:'Review',exact:true}).click();await department.getByLabel('Sanction amount (INR)',{exact:false}).fill('42.50');await department.getByLabel('Benefit period',{exact:false}).fill('Synthetic UI acceptance period');await department.getByLabel('Decision reason',{exact:false}).fill('Synthetic eligibility reviewed by assigned scheme officer.');const sanctionResponse=department.waitForResponse(r=>r.url().includes('/decision')&&r.request().method()==='POST');await department.getByRole('button',{name:'Record sanction',exact:true}).click();const payment=await(await sanctionResponse).json();assert.ok(payment.reference);await department.getByRole('tab',{name:'Payment register',exact:true}).click();await department.locator('button.payment-row').filter({hasText:payment.reference}).click();await department.getByRole('button',{name:'Process payment',exact:true}).click();await department.getByRole('heading',{name:'Record a reversal',exact:true}).waitFor();console.log('PASS: department sanction and simulated payment',payment.reference);
  await resident.goto(BASE_URL+'/my/payments');await resident.getByText(payment.reference,{exact:false}).waitFor();assert.match(await resident.locator('main').innerText(),/Paid|Completed/);await resident.screenshot({path:'/tmp/kutumb-complete-product.png',fullPage:true});console.log('PASS: resident sees source-reported payment');assert.equal(errors.length,0,errors.join('\n'));console.log('BROWSER WORKFLOW PASS: OTP → enrollment → separate verification/approval → family → referral → sanction → simulated payment → resident report');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
