/** End-to-end API acceptance on the isolated synthetic environment. */
import assert from 'node:assert/strict';
import {mkdir, writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const base=(process.env.BASE_URL||'http://127.0.0.1:8095')+'/api/v1';
const stamp=Date.now();
const results=[];
async function check(name,fn){const start=performance.now();try{await fn();results.push({name,passed:true,ms:Math.round(performance.now()-start)});console.log('PASS '+name);}catch(error){results.push({name,passed:false,error:String(error),ms:Math.round(performance.now()-start)});console.error('FAIL '+name+'\n'+String(error));}}
function client(){
 let cookie='',csrf='';
 return {
  async request(path,method='GET',body,expected=200,options={}){
   const headers={...(cookie?{Cookie:cookie}:{}),...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...(csrf&&!options.noCsrf?{'X-CSRF-Token':csrf}:{}),...(options.key?{'Idempotency-Key':options.key}:{}),...options.headers};
   const res=await fetch(base+path,{method,headers,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});
   const setCookie=res.headers.get('set-cookie');if(setCookie)cookie=setCookie.split(';')[0];
   const text=await res.text();let data;try{data=JSON.parse(text);}catch{data=text;}
   if(Array.isArray(expected))assert(expected.includes(res.status),`${method} ${path}: ${res.status} ${text.slice(0,400)}`);else assert.equal(res.status,expected,`${method} ${path}: ${text.slice(0,400)}`);
   if(data?.csrf_token)csrf=data.csrf_token;
   return {data,res};
  },
  async login(email){return (await this.request('/auth/login','POST',{email,password:'DemoPass@123!'})).data;},
  cookie:()=>cookie
 };
}
const anon=client(),resident=client(),other=client(),verifier=client(),approver=client(),admin=client(),department=client(),fresh=client();
let app,family,scheme,referral,payment,grievance,partner,partnerToken,challenge;
const enrollment={applicant:{name:'Acceptance Test Resident',name_gu:'પરીક્ષણ રહેવાસી',phone:'9000099991'},address:{address_line:'17 Test Lane',locality:'Test Area',taluka:'Ahmedabad City',district:'Ahmedabad',pincode:'380001'},members:[{client_id:'self',name:'Acceptance Test Resident',name_gu:'પરીક્ષણ રહેવાસી',dob:'1991-04-14',relationship:'self'},{client_id:'child',name:'Acceptance Test Child',name_gu:'પરીક્ષણ બાળક',dob:'2016-08-21',relationship:'child'}],declarations:{accuracy:true,authority:true}};

await check('Health and test-environment configuration',async()=>{const {data}=await anon.request('/health');assert.equal(data.status,'ok');const c=(await anon.request('/public/config')).data;assert(c.mode);assert(c.languages.includes('gu'));});
await check('Unauthenticated personal endpoints require sign-in',async()=>{for(const p of ['/dashboard','/families/mine','/applications','/benefits','/payments','/admin/overview'])await anon.request(p,'GET',undefined,401);});
await check('Public scheme catalogue and bounded pagination',async()=>{const d=(await anon.request('/schemes?page_size=2')).data;assert(d.items.length<=2);assert(d.total>=2);await anon.request('/schemes?page_size=10000','GET',undefined,422);scheme=(await anon.request('/schemes?page_size=100')).data.items.find(s=>['demo_connected','connected'].includes(s.capability));assert(scheme,'A connected simulator scheme is seeded');});
await check('OTP challenge is one-time and identity-bound',async()=>{const helpers=(await anon.request('/auth/demo-accounts')).data;const seed=helpers.items.find(x=>x.email==='resident@demo.local');assert(seed);const identifier=seed.mobile||seed.public_id||'9000000001';challenge=(await resident.request('/auth/challenges','POST',{identifier,purpose:'sign_in'})).data;assert(challenge.challenge_id);await resident.request('/auth/verify','POST',{challenge_id:challenge.challenge_id,code:'000000'},[400,401,422]);const auth=(await resident.request('/auth/verify','POST',{challenge_id:challenge.challenge_id,code:'123456'})).data;assert.equal(auth.user.role,'resident');await resident.request('/auth/verify','POST',{challenge_id:challenge.challenge_id,code:'123456'},[400,401,409]);});
await check('Staff session setup',async()=>{await verifier.login('verifier@demo.local');await approver.login('approver@demo.local');await admin.login('admin@demo.local');await department.login('department@demo.local');await other.login('other.resident@demo.local');});
await check('CSRF and foreign-origin writes rejected',async()=>{await resident.request('/grievances','POST',{category:'service',subject:'CSRF test',description:'This write must not persist.'},403,{noCsrf:true});await resident.request('/grievances','POST',{category:'service',subject:'Origin test',description:'This write must not persist.'},403,{headers:{Origin:'https://attacker.invalid'}});});
await check('Resident cannot open staff/admin workspaces',async()=>{for(const p of ['/staff/applications','/admin/overview','/admin/audit','/staff/payments'])await resident.request(p,'GET',undefined,403);});
await check('Cross-family access and public enumeration denied',async()=>{const f=(await resident.request('/families/mine')).data;await other.request('/families/'+f.id,'GET',undefined,[403,404]);const d=(await other.request('/registry/check','POST',{reference:f.public_id})).data;assert.notEqual(d.family_id,f.id);const b=(await resident.request('/benefits')).data;assert(Array.isArray(b.items));});
await check('Mobile verification creates a resident account, not a family',async()=>{const mobile='9'+String(stamp).slice(-9);const c=(await fresh.request('/auth/challenges','POST',{identifier:mobile,purpose:'register',display_name:'Acceptance '+stamp,language:'en'})).data;const a=(await fresh.request('/auth/verify','POST',{challenge_id:c.challenge_id,code:'123456'})).data;assert.equal(a.user.role,'resident');assert(!a.user.person_id);await fresh.request('/families/mine','GET',undefined,404);});
await check('Draft creation is durable and not a submitted application',async()=>{app=(await fresh.request('/applications','POST',{kind:'enrollment',branch:'no_ration',district:'Ahmedabad',payload:{},step:1},[200,201])).data;assert.equal(app.status,'draft');assert(!app.reference);assert.equal((await fresh.request('/applications/'+app.id)).data.id,app.id);});
await check('Empty enrollment cannot submit',async()=>{await fresh.request('/applications/'+app.id+'/submit','POST',{revision:app.revision},422,{key:randomUUID()});});
await check('Draft rejects protected fields and stale revisions',async()=>{await fresh.request('/applications/'+app.id,'PATCH',{revision:app.revision,payload:{aadhaar_number:'000000000000'},step:1},422);app=(await fresh.request('/applications/'+app.id,'PATCH',{revision:app.revision,payload:enrollment,step:5})).data;await fresh.request('/applications/'+app.id,'PATCH',{revision:1,payload:enrollment,step:5},409);});
await check('Submission retry creates one receipt and not an ID',async()=>{const key=randomUUID(),body={revision:app.revision};const a=(await fresh.request('/applications/'+app.id+'/submit','POST',body,200,{key})).data;const b=(await fresh.request('/applications/'+app.id+'/submit','POST',body,200,{key})).data;assert.equal(a.reference,b.reference);assert.equal(a.status,'submitted');assert(!a.family_id);app=a;await fresh.request('/applications/'+app.id+'/submit','POST',{revision:999},409,{key});});
await check('Another resident cannot read an application or its receipt',async()=>{await resident.request('/applications/'+app.id,'GET',undefined,[403,404]);await resident.request('/applications/'+app.id+'/receipt','GET',undefined,[403,404]);});
await check('An approver cannot skip verification',async()=>{await approver.request('/staff/applications/'+app.id+'/action','POST',{action:'approve',reason:'Approval must await independent verification',revision:app.revision},[400,403,409],{key:randomUUID()});});
await check('Verifier can review but cannot approve',async()=>{app=(await verifier.request('/staff/applications/'+app.id+'/action','POST',{action:'start_review',reason:'Initial review started',revision:app.revision},200,{key:randomUUID()})).data;await verifier.request('/staff/applications/'+app.id+'/action','POST',{action:'approve',reason:'Forbidden self approval attempt',revision:app.revision},403,{key:randomUUID()});app=(await verifier.request('/staff/applications/'+app.id+'/action','POST',{action:'verify',reason:'Synthetic evidence and address checked',revision:app.revision},200,{key:randomUUID()})).data;assert.equal(app.status,'verified');});
await check('Approval atomically issues family/person records and timeline',async()=>{app=(await approver.request('/staff/applications/'+app.id+'/action','POST',{action:'approve',reason:'Independent review completed',revision:app.revision},200,{key:randomUUID()})).data;assert.equal(app.status,'implemented');family=(await fresh.request('/families/mine')).data;assert(family.public_id);assert.equal(family.members.length,2);assert(app.events.some(e=>e.to_status==='approved'));assert(app.events.some(e=>e.to_status==='implemented'));assert.equal((await fresh.request('/applications/'+app.id+'/receipt')).data.application.id,app.id);});
await check('Address change does not mutate verified record before approval',async()=>{const address={...family.address,address_line:'22 Reviewed Test Lane'};let change=(await fresh.request('/changes','POST',{family_id:family.id,change_type:'address',payload:{address}},[200,201])).data;assert.notEqual((await fresh.request('/families/mine')).data.address.address_line,address.address_line);change=(await fresh.request('/applications/'+change.id+'/submit','POST',{revision:change.revision},200,{key:randomUUID()})).data;change=(await verifier.request('/staff/applications/'+change.id+'/action','POST',{action:'start_review',reason:'Address review started',revision:change.revision},200,{key:randomUUID()})).data;change=(await verifier.request('/staff/applications/'+change.id+'/action','POST',{action:'verify',reason:'Address evidence reviewed',revision:change.revision},[200],{key:randomUUID()})).data;await approver.request('/staff/applications/'+change.id+'/action','POST',{action:'approve',reason:'Address correction approved',revision:change.revision},200,{key:randomUUID()});const updated=(await fresh.request('/families/mine')).data;assert.equal(updated.public_id,family.public_id);assert.equal(updated.address.address_line,address.address_line);family=updated;});
await check('Connected referral is persisted and idempotent',async()=>{const key=randomUUID();referral=(await fresh.request('/scheme-applications','POST',{scheme_id:scheme.id,consent:true},[200,201],{key})).data;const replay=(await fresh.request('/scheme-applications','POST',{scheme_id:scheme.id,consent:true},[200,201],{key})).data;assert.equal(referral.id,replay.id);});
await check('Resident cannot sanction payments',async()=>{await fresh.request('/staff/scheme-applications/'+referral.id+'/decision','POST',{action:'sanction',reason:'Not authorised',amount:'1000.00',period:'September 2026'},403,{key:randomUUID()});});
await check('Scoped department sanction creates one payment order',async()=>{const key=randomUUID(),body={action:'sanction',reason:'Test application approved by owning department',amount:'1000.00',period:'September 2026'};payment=(await department.request('/staff/scheme-applications/'+referral.id+'/decision','POST',body,200,{key})).data;assert.equal(payment.status,'sanctioned');assert.equal((await department.request('/staff/scheme-applications/'+referral.id+'/decision','POST',body,200,{key})).data.id,payment.id);});
await check('Payment failure, retry and reversal remain traceable',async()=>{payment=(await department.request('/staff/payments/'+payment.id+'/process','POST',{revision:payment.revision,outcome:'failed',reason:'Provider failure fixture'},200,{key:randomUUID()})).data;assert.equal(payment.status,'failed');payment=(await department.request('/staff/payments/'+payment.id+'/process','POST',{revision:payment.revision,outcome:'paid',reason:'Provider retry settled'},200,{key:randomUUID()})).data;assert.equal(payment.status,'paid');payment=(await department.request('/staff/payments/'+payment.id+'/reverse','POST',{revision:payment.revision,reason:'Test reconciliation reversal'},200,{key:randomUUID()})).data;assert.equal(payment.status,'reversed');for(const state of ['sanctioned','processing','failed','paid','reversed'])assert(payment.events.some(e=>e.to_status===state));});
await check('Payment register is owner scoped; passbook reports reversal',async()=>{assert.equal((await fresh.request('/payments/'+payment.id)).data.id,payment.id);await resident.request('/payments/'+payment.id,'GET',undefined,404);const entries=(await fresh.request('/benefits')).data.items;assert(entries.some(b=>b.source_reference===payment.provider_reference&&b.status==='reversed'));});
await check('Grievance receipt, staff response and cross-user privacy',async()=>{grievance=(await fresh.request('/grievances','POST',{category:'benefit',subject:'Payment reconciliation question',description:'Please review my synthetic payment report.'},[200,201])).data;assert(grievance.reference);await resident.request('/grievances/'+grievance.id,'GET',undefined,[403,404]);await admin.request('/staff/grievances/'+grievance.id+'/action','POST',{status:'in_review',response:'Independent review has started.'});await admin.request('/staff/grievances/'+grievance.id+'/action','POST',{status:'resolved',response:'The synthetic payment source was checked.'});assert.equal((await fresh.request('/grievances/'+grievance.id)).data.status,'resolved');});
await check('Publishing is role-restricted and revision-controlled',async()=>{const pages=(await admin.request('/admin/content')).data.items;const page=pages.find(x=>x.slug==='about')||pages[0];assert(page);await fresh.request('/admin/content/'+page.slug,'PUT',{title:page.title,title_gu:page.title_gu,body:page.body,body_gu:page.body_gu,revision:page.revision},403);await admin.request('/admin/content/'+page.slug,'PUT',{title:page.title,title_gu:page.title_gu,body:page.body,body_gu:page.body_gu,revision:page.revision});await admin.request('/admin/content/'+page.slug,'PUT',{title:page.title,title_gu:page.title_gu,body:page.body,body_gu:page.body_gu,revision:page.revision},409);});
await check('Integration request, approval and scoped resolve',async()=>{partner=(await department.request('/departments/clients','POST',{name:'Acceptance client '+stamp,purpose:'Verify synthetic family status only',requested_scopes:['family:verify']},[200,201])).data;const approved=(await admin.request('/admin/clients/'+partner.id+'/approve','POST',{approved_scopes:['family:verify'],approved_scheme_ids:[]})).data;partnerToken=approved.credential||approved.token||approved.api_key;assert(partnerToken,'Issued once credential');await anon.request('/integration/resolve','POST',{public_id:family.public_id,purpose:'Different unapproved purpose'},403,{headers:{Authorization:'Bearer '+partnerToken}});const value=(await anon.request('/integration/resolve','POST',{public_id:family.public_id,purpose:'Verify synthetic family status only'},200,{headers:{Authorization:'Bearer '+partnerToken}})).data;assert.equal(value.public_id,family.public_id);assert(!value.members&&!value.address);});
await check('Revoked integration credentials stop working',async()=>{await admin.request('/admin/clients/'+partner.id+'/revoke','POST',{});await anon.request('/integration/resolve','POST',{public_id:family.public_id,purpose:'Revocation check'},[401,403],{headers:{Authorization:'Bearer '+partnerToken}});});
await check('Private responses prevent caching and expose no stack traces',async()=>{const {res,data}=await fresh.request('/dashboard');assert.match(res.headers.get('cache-control')||'',/no-store/);assert(!JSON.stringify(data).includes('password_hash'));await fresh.request('/applications/not-an-owned-id','GET',undefined,[404,422]);});
await check('Audit and durable outbox exist',async()=>{const audit=(await admin.request('/admin/audit')).data;assert(audit.total>0);const history=(await fresh.request('/access-history')).data;assert(history.items.length>0);const notifications=(await fresh.request('/notifications')).data;assert(notifications.items.length>0);});
await check('Logout revokes server session',async()=>{await fresh.request('/auth/logout','POST',{});await fresh.request('/auth/me','GET',undefined,401);});

const summary={run_at:new Date().toISOString(),base_url:base,scope:'Synthetic local API workflow, security and provider-adapter acceptance; not a production/security certification or statewide benchmark',passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results};
await mkdir('docs/test-results',{recursive:true});await writeFile('docs/test-results/api-results.json',JSON.stringify(summary,null,2)+'\n');
console.log(JSON.stringify({passed:summary.passed,failed:summary.failed}));process.exitCode=summary.failed?1:0;
